#!/usr/bin/perl

use strict;
use warnings;

use File::Copy qw(copy);
use File::Find qw(find);
use File::LibMagic;
use File::Temp;
use Getopt::Long qw(GetOptions);

my $PROGRAM_NAME = 'brp-mangle-shebangs';
my $SHORT_USAGE =
"usage: $PROGRAM_NAME [--files <regexp>] [--files-from <file>] [--shebangs <regexp>] [--shebangs-from <file>]";

sub print_usage_error {
    print STDERR "$SHORT_USAGE\n";
}

sub print_usage {
    print <<EOF;
$SHORT_USAGE
  --files: extended regexp of files to ignore'
  --files-from: file containing a list of extended regexps of files to ignore'
  --shebangs: extended regexp of shebangs to ignore'
  --shebangs-from: file containing a list of extended regexps of shebangs to ignore'
EOF
}

sub warning {
    my $message = shift;
    print STDERR "*** WARNING: $message\n";
}

sub error {
    my $message = shift;
    print STDERR "*** ERROR: $message\n";
}

my $RPM_BUILD_ROOT = $ENV{'RPM_BUILD_ROOT'};

if (   !defined $RPM_BUILD_ROOT
    or !length $RPM_BUILD_ROOT
    or $RPM_BUILD_ROOT eq '/' )
{
    exit 0;
}

my @exclude_files = ();
my $exclude_files_from;
my @exclude_shebangs = ();
my $exclude_shebangs_from;

unless (
    GetOptions(
        'files=s'         => \@exclude_files,
        'files-from=s'    => \$exclude_files_from,
        'shebangs=s'      => \@exclude_shebangs,
        'shebangs-from=s' => \$exclude_shebangs_from,
        'help|usage|?|h'  => sub { print_usage; exit 0; },
    )
  )
{
    print_usage_error;
    exit 1;
}

if ( defined $exclude_files_from ) {
    my $exclude_files_handle;
    unless ( open $exclude_files_handle,
        '<:encoding(utf8)', $exclude_files_from )
    {
        error "Cannot read file $exclude_files_from\n";
        exit 1;
    }
    while (<$exclude_files_handle>) {
        chomp;
        push( @exclude_files, $_ ) if length $_;
    }
    close $exclude_files_handle;
}

if ( defined $exclude_shebangs_from ) {
    my $exclude_shebangs_handle;
    unless ( open $exclude_shebangs_handle,
        '<:encoding(utf8)', $exclude_shebangs_from )
    {
        error "Cannot read file $exclude_shebangs_from\n";
        exit 1;
    }
    while (<$exclude_shebangs_handle>) {
        chomp;
        push( @exclude_shebangs, $_ ) if length $_;
    }
    close $exclude_shebangs_handle;
}

my $fail  = 0;
my $magic = File::LibMagic->new;

sub remove_executable_bit {
    my $filename  = shift;
    my @stats     = stat $filename;
    my $old_mode  = $stats[2] & 07777;
    my $old_mtime = $stats[9];
    chmod $old_mode & 07666, $filename;
    utime $old_mtime, $old_mtime, $filename;
}

sub mangle_shebang {
    my $filename = $_;
    return unless -f -r -x $filename;
    my $path = $File::Find::name;
    for my $pattern (@exclude_files) {
        return if $filename =~ /$pattern/;
    }

    my $mime_type = $magic->info_from_filename($filename)->{mime_type};
    return unless $mime_type =~ m@^text/|^application/javascript@;

    my $handle;
    unless ( open $handle, '<', $filename ) {
        error "Failed to open file $path";
        $fail = 1;
        return;
    }
    my $orig_shebang = <$handle>;
    unless ( defined $orig_shebang ) {
        warning
          "Cannot read the first line from $path, removing executable bit";
        remove_executable_bit $filename;
        return;
    }
    chomp $orig_shebang;
    close $handle;

    unless ( $orig_shebang =~ s/^#!// ) {
        warning
          "$path is executable but has no shebang, removing executable bit";
        remove_executable_bit $filename;
        return;
    }

    # Treat "#! /path/to " as "#!/path/to"
    $orig_shebang =~ s/^\s+//;
    $orig_shebang =~ s/\s+$//;

    unless ( length $orig_shebang ) {
        warning
          "$path is executable but has empty shebang, removing executable bit";
        remove_executable_bit $filename;
        return;
    }

    unless ( $orig_shebang =~ /\// ) {
        error "$path has shebang which doesn't start with '/' ($orig_shebang)";
        $fail = 1;
        return;
    }

    return unless $orig_shebang =~ m@^/(?:usr/)?(?:bin|sbin)/@;

    for my $pattern (@exclude_shebangs) {
        return if $orig_shebang =~ /$pattern/;
    }

    my $shebang = $orig_shebang;

    # Replace "special" env shebang:
    # /whatsoever/env -whatever /whatever/foo → /whatever/foo
    $shebang =~ s@^(?:.+)/env(?: -[^ ]+)* /(.+)$@/$1@;

    # /whatsoever/env -whatever foo → /whatsoever/foo
    $shebang =~ s@^(.+/)env(?: -[^ ]+)* (.+)$@$1$2@;

    # If the shebang now starts with /bin, change it to /usr/bin
    # https://bugzilla.redhat.com/show_bug.cgi?id=1581757
    $shebang =~ s@^/bin/@/usr/bin/@;

    if ( $shebang =~ m@/usr/bin/python(?:\s|$)@ ) {
        error
"ambiguous python shebang in $path: #!$orig_shebang. Change it to python3 (or python2) explicitly.";
        $fail = 1;
        return;
    }

    return if $shebang eq $orig_shebang;

    print "mangling shebang in $path from $orig_shebang to #!$shebang\n";
    my $old_mtime = ( stat $filename )[9];
    my $temp_file = File::Temp->new;
    copy $filename, $temp_file;
    my $write_handle;
    unless ( open $write_handle, '>', $filename ) {
        error "Failed to open file $path for writing";
        $fail = 1;
        return;
    }
    seek $temp_file, 0, 0;
    while ( defined( my $line = <$temp_file> ) ) {
        print $write_handle ( $. == 1 ? "#!$shebang\n" : $line );
    }
    utime $old_mtime, $old_mtime, $write_handle;
    unless ( close $write_handle ) {
        error "Failed to complete write operation to file $path";
        $fail = 1;
    }
}

chdir $RPM_BUILD_ROOT or die "Can't cd to $RPM_BUILD_ROOT\n";
find \&mangle_shebang, '.';
exit $fail;
